### ISSUE TITLE
Just wanted to thank you!

### ISSUE THREAD

**Issue by FaserF** [Findus23/voice_pack_dreame#1]
As discussions are disabled here:

Wow, I was searching everywhere why my voice pack couldnt be loaded onto the robot. Yours worked so great and easy on my Dreame Z10 Pro 👍🏼 

THANK YOU!

Maybe as a feature request, could you port the custom voice pack from here? https://github.com/arner/roborock-glados
The default one is fine, but the custom one from arner ist definitly more funny

**Comment by Findus23** [comment]
You're welcome :)

> Maybe as a feature request, could you port the custom voice pack from here? https://github.com/arner/roborock-glados

Isn't that the same as the one I used for inspiration:
https://github.com/ccoors/dreame_voice_packs

At least they both are using https://glados.c-net.org/ for the voice generation

**Comment by FaserF** [comment]
As far as I have seen it, the current one ist just a translation of the official sentences just with Glados speech.

the link that I have mentioned is not a direct translation, same meaning just funnier.

example: 
Sentence: „Finished cleaning“
This glados voice pack: „Finished cleaning“
From the link above with glados speech: „I have finished cleaning… I think… I don’t care“

i hope it’s understandable written down.

**Comment by Findus23** [comment]
Ah, indeed I am just using the original sentences (and checked all of them with my robot to confirm they are correct).

If you want other lines, you could edit the [sound_list.csv](https://github.com/Findus23/voice_pack_dreame/blob/main/sound_list.csv) and rerun the main script (or create a pull request for me to rerun the script)

**Comment by FaserF** [comment]
Thanks, just tried that locally, but seems my .ogg files wont work
