### ISSUE TITLE
Prepackaged voice_pack.tar.gz broken

### ISSUE THREAD

**Issue by shouya** [Findus23/voice_pack_dreame#3]
The prepackaged voice_pack.tar.gz (md5sum: c34109f9012b855a42096d7987dd9bd5) failed to work for me. So I checked the file. When I attempt to unpack it (`tar xzvf voice_pack.tar.gz`), it seems the file was broken:

```
$ tar xzvf voice_pack.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

After cloning the repo and repackaging the voices myself (`tar czvf glados.tar.gz *.ogg`) and uploaded it somewhere, I'm able to get a working GLaDOS voice.

**Comment by shouya** [comment]
Just for reference:

```
url: https://transfer.sh/D0NVWH/glados.tar.gz
md5sum: 756338796c66bf889587435c33c109c4
size: 4325080
```

**Comment by Findus23** [comment]
Oh, you are totally right. I just checked the file and while I named it .tar.gz, it is not gz compressed, but just a regular tar file.
While the PR is really nice, I'd prefer to keep the tar file like before and just actually gzip it.
